version: '3.7'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/symfony
    depends_on:
      - mysql

  nginx:
#    build:
#      context: .
#      dockerfile: docker/nginx/Dockerfile
    image: nginx:latest
    ports:
      - "9150:80"
    volumes:
      - .:/var/www/symfony:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    image: mysql:8.2.0
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data_stfalcon:/var/lib/mysql
    ports:
      - "9408:3306"

volumes:
  db_data_stfalcon:
